### ISSUE TITLE
Parameter Documentation

### ISSUE THREAD

**Issue by nicholas-maltbie** [nicholas-maltbie/gddoc2yml#13]
Right now, godot docs support a `[param name]` tag for referencing a parameter. There are some sections of the docs that support documenting the parameter on it's own line. I would like to expand the documentation parser in gdxml2yml.py to find these `[param name]` tags and include their info in the parameter documentation in the yml.

Requirements:
* When parsing the description/text for a method (or anything with a parameter). If the `[param name]` tag starts a new line (ignoring any whitespace at the start of the line), then assume that documentation is for the parameter and treat it like the `<param name="name">param description</param>` tag from C# xml docs. This may require adding support for parsing a `[/param]` tag to know when the parameter documentation ends. 

Example:

The parameter `stream` for method `audio_track_insert_key` is on its own line. When parsed, the param description should be moved to its own line.

```xml
<method name="audio_track_insert_key">
  <return type="int" />
  <param index="0" name="track_idx" type="int" />
  <param index="1" name="time" type="float" />
  <param index="2" name="stream" type="Resource" />
  <param index="3" name="start_offset" type="float" default="0" />
  <param index="4" name="end_offset" type="float" default="0" />
  <description>
    Inserts an Audio Track key at the given [param time] in seconds. The [param track_idx] must be the index of an Audio Track.
    [param stream] is the [AudioStream] resource to play. [param start_offset] is the number of seconds cut off at the beginning of the audio stream, while [param end_offset] is at the ending.
  </description>
</method>
```

should become

```yml
- uid: Animation.audio_track_insert_key(int,float,Resource,float,float)
  commentId: M:Animation.audio_track_insert_key(int,float,Resource,float,float)
  id: audio_track_insert_key(int,float,Resource,float,float)
  langs:
  - gdscript
  - csharp
  name: audio_track_insert_key(int, float, Resource, float, float)
  nameWithType: Animation.audio_track_insert_key(int, float, Resource, float, float)
  type: Method
  syntax:
    content: int audio_track_insert_key(int track_idx, float time, Resource stream,
      float start_offset, float end_offset)
    parameters:
    - id: track_idx
      type: int
    - id: time
      type: float
    - id: stream
      type: Resource
      description: '``stream`` is the <xref href="AudioStream" data-throw-if-not-resolved="false"></xref>
        resource to play. ``start_offset`` is the number of seconds cut off at the beginning
        of the audio stream, while ``end_offset`` is at the ending.'
    - id: start_offset
      type: float
    - id: end_offset
      type: float
  summary: 'Inserts an Audio Track key at the given ``time`` in seconds. The ``track_idx``
    must be the index of an Audio Track.'
  parent: Animation
```

A future idea could be to include a new `[return]` and `[/return]` tags to describe return type as well.

References:

https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_documentation_comments.html#bbcode-and-class-reference
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/recommended-tags#param
