### ISSUE TITLE
Direct XRefMap to Godot Docs

### ISSUE THREAD

**Issue by nicholas-maltbie** [nicholas-maltbie/gddoc2yml#21]
Make an xrefmap.yml that links directly to the godot docs webiste:
* https://docs.godotengine.org/en/stable/classes/

Get the ids for each link and create a mapping from the docfx ids directly to the class reference in the godot site.

Entries should look something like this:

```yml
- uid: Vector3
  name: Vector3
  href: https://docs.godotengine.org/en/stable/classes/class_vector3.html
  commentId: T:Vector3
  nameWithType: Vector3
- uid: Vector3.AXIS_X
  name: AXIS_X
  href: https://docs.godotengine.org/en/stable/classes/class_vector3.html#class-vector3-constant-axis-x
  commentId: F:Vector3.AXIS_X
  nameWithType: Vector3.AXIS_X
...
```
